# Generated by Django 3.2 on 2024-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('Sell', 'Sell Stock'), ('Buy', 'Buy Stock'), ('Hold', 'Hold Stock')], default='Hold', max_length=5),
        ),
    ]
